- hosts: all

  tasks:
    - name: Install yum packages
      package:
        name: "{{ item }}"
        state: present
      become: True
      with_items:
        - python-pip

    - name: Ensure pip conf directory
      file:
        path: "{{ ansible_env.HOME }}/.pip"
        state: directory
        recurse: yes
      become: True

    - name: Update pip local mirror
      template:
        src: etc/pip.conf
        dest: "{{ ansible_env.HOME }}/.pip/daemon.json"

    - name: Install docker package
      pip:
        name: docker
