gitlab:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: gitlab
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://192.168.10.61:30081'
  ports:
    - '30081:30081'
    - '10443:443'
    - '10022:22'
  volumes:
    - './data/gitlab/config:/etc/gitlab'
    - './data/gitlab/logs:/var/log/gitlab'
    - './data/gitlab/data:/var/opt/gitlab'
