## PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  capacity:          
    storage: 100Gi
  accessModes:       
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - hard
  - nfsvers=4.1    
  nfs:
    server: 192.168.10.37
    path: /MotionGear/DEV_SHARED_NFS/DEV
---
## PVC
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
spec:
  resources:
    requests:
      storage: 100Gi
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      app: postgresql
